import ReactDOM from 'react-dom/client'
import './fast-runtime'
import App from './App'
import './styles.css'
import './mobile.css'
import './review-enhancer.css'
import './welcome-qr.css'
import './certificate-eligibility.css'
import './review-overflow-fix.css'
import './review-enhancer'
import './welcome-qr'
import './handoff-polish'
import './certificate-eligibility'

ReactDOM.createRoot(document.getElementById('root')).render(<App />)
